language: php
install:
  - composer install
matrix:
    fast_finish: true
    allow_failures:
        -   php: "7.3"
php:
    - "7.1"
    - "7.2"
    - "7.3"
script:
    #- mkdir -p build/logs
    #- phpunit --coverage-clover build/logs/clover.xml
after_success:
#- travis_retry composer require --dev php-coveralls/php-coveralls\
#    && php vendor/bin/php-coveralls -v
